# docker-compose.yml
version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kb
    ports: ["5432:5432"]
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql
